/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module Test1(CLK, EN, D_IN, D_OUT);
  wire _0_;
  input CLK;
  input D_IN;
  output D_OUT;
  input EN;
  sky130_fd_sc_hd__mux2_2 _1_ (
    .A0(D_OUT),
    .A1(D_IN),
    .S(EN),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(CLK),
    .D(_0_),
    .Q(D_OUT)
  );
endmodule
