/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module Test14(CLK, En1, D_IN1, D_IN2, OUT1, OUT2, OUT3);
  wire _0_;
  wire _1_;
  wire _2_;
  input CLK;
  input D_IN1;
  input D_IN2;
  input [1:0] En1;
  output OUT1;
  output OUT2;
  output OUT3;
  sky130_fd_sc_hd__mux2_2 _3_ (
    .A0(OUT2),
    .A1(D_IN2),
    .S(En1[0]),
    .X(_1_)
  );
  sky130_fd_sc_hd__mux2_2 _4_ (
    .A0(OUT3),
    .A1(D_IN2),
    .S(En1[1]),
    .X(_2_)
  );
  sky130_fd_sc_hd__mux2_2 _5_ (
    .A0(OUT1),
    .A1(D_IN1),
    .S(En1[0]),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _6_ (
    .CLK(CLK),
    .D(_2_),
    .Q(OUT3)
  );
  sky130_fd_sc_hd__dfxtp_1 _7_ (
    .CLK(CLK),
    .D(_1_),
    .Q(OUT2)
  );
  sky130_fd_sc_hd__dfxtp_1 _8_ (
    .CLK(CLK),
    .D(_0_),
    .Q(OUT1)
  );
endmodule
