/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module Test11(CLK, En1, En2, D_IN, OUT1, OUT2);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input CLK;
  input [4:0] D_IN;
  input En1;
  input En2;
  output [4:0] OUT1;
  output [4:0] OUT2;
  sky130_fd_sc_hd__mux2_2 _10_ (
    .A0(OUT1[1]),
    .A1(D_IN[1]),
    .S(En1),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_2 _11_ (
    .A0(OUT1[0]),
    .A1(D_IN[0]),
    .S(En1),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_2 _12_ (
    .A0(OUT2[3]),
    .A1(D_IN[1]),
    .S(En2),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux2_2 _13_ (
    .A0(OUT2[2]),
    .A1(D_IN[2]),
    .S(En2),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_2 _14_ (
    .A0(OUT1[2]),
    .A1(D_IN[2]),
    .S(En1),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_2 _15_ (
    .A0(OUT2[1]),
    .A1(D_IN[3]),
    .S(En2),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_2 _16_ (
    .A0(OUT2[0]),
    .A1(D_IN[4]),
    .S(En2),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_2 _17_ (
    .A0(OUT1[4]),
    .A1(D_IN[4]),
    .S(En1),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_2 _18_ (
    .A0(OUT1[3]),
    .A1(D_IN[3]),
    .S(En1),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_2 _19_ (
    .A0(OUT2[4]),
    .A1(D_IN[0]),
    .S(En2),
    .X(_09_)
  );
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(CLK),
    .D(_03_),
    .Q(OUT1[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(CLK),
    .D(_01_),
    .Q(OUT1[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _22_ (
    .CLK(CLK),
    .D(_07_),
    .Q(OUT2[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _23_ (
    .CLK(CLK),
    .D(_05_),
    .Q(OUT2[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _24_ (
    .CLK(CLK),
    .D(_02_),
    .Q(OUT1[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _25_ (
    .CLK(CLK),
    .D(_04_),
    .Q(OUT1[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _26_ (
    .CLK(CLK),
    .D(_00_),
    .Q(OUT1[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _27_ (
    .CLK(CLK),
    .D(_09_),
    .Q(OUT2[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _28_ (
    .CLK(CLK),
    .D(_08_),
    .Q(OUT2[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _29_ (
    .CLK(CLK),
    .D(_06_),
    .Q(OUT2[1])
  );
endmodule
