/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module Test4(CLK, EN, D_IN1, D_IN2, OUT);
  wire _0_;
  input CLK;
  input D_IN1;
  input D_IN2;
  wire D_OUT;
  input EN;
  output OUT;
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(D_IN2),
    .B(D_OUT),
    .X(OUT)
  );
  sky130_fd_sc_hd__mux2_2 _2_ (
    .A0(D_OUT),
    .A1(D_IN1),
    .S(EN),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _3_ (
    .CLK(CLK),
    .D(_0_),
    .Q(D_OUT)
  );
endmodule
